name: Test

on: pull_request

jobs:
  jest:
    name: jest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v10
      uses: actions/setup-node@v1
      with:
        node-version: 10.15.0
    - name: yarn install
      run: yarn install
    - name: run tests
      run: yarn test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
